# Pandas Tricks


## Print each row

[stackoverflow: how to iterate over rows in a dataframe in pandas](https://stackoverflow.com/questions/16476924/how-to-iterate-over-rows-in-a-dataframe-in-pandas)

In [3]:
import pandas as pd
df = pd.DataFrame({'c1': [10, 11, 12], 'c2': [100, 110, 120]})

for index, row in df.iterrows():
    print(row['c1'], row['c2'])

10 100
11 110
12 120

## Filter rows by column value

[Python | Pandas Series.str.contains() - GeeksforGeeks](https://www.geeksforgeeks.org/python-pandas-series-str-contains/)

```python
pat = '假[\s\S]{0,6}新聞|假[\s\S]{0,6}消息|不實[\s\S]{0,6}新聞|不實[\s\S]{0,6}消息|假[\s\S]{0,6}訊息|不實[\s\S]{0,6}訊息'
filtered_comment = comment[comment['ccontent'].str.contains(pat=pat, na=False)]
```

## Filter row/column by regular expression

In [10]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['one', 'two', 'three'])

# select columns by regular expression
df.filter(regex='e$', axis=1)

# select rows containing 'bbi
df.filter(like='bbi', axis=0) # defualt: axis=1 for columns

        one  two  three
rabbit    4    5      6

## groupby and summarize(Pivot)

[Reshaping and pivot tables — pandas 1.4.2 documentation (pydata.org)](https://pandas.pydata.org/docs/user_guide/reshaping.html)

### Multiple factors to one new column

```python
count = raw.groupby(["authorDisplayName", "isSimplified2"]).size().reset_index(name="Time")
```

### One column summarized to multiple columns

[https://stackoverflow.com/questions/14529838/apply-multiple-functions-to-multiple-groupby-columns/53096340](https://stackoverflow.com/questions/14529838/apply-multiple-functions-to-multiple-groupby-columns/53096340)

```python
print(
    animals
    .groupby('kind')
    .height
    .agg(
        min_height='min',
        max_height='max',
    )
)
#       min_height  max_height
# kind                        
# cat          9.1         9.5
# dog          6.0        34.0
```
---
```python
print(
    animals
    .groupby('kind')
    .agg(
        min_height=('height', 'min'),
        max_height=('height', 'max'),
        average_weight=('weight', np.mean),
    )
)
#       min_height  max_height  average_weight
# kind                                        
# cat          9.1         9.5            8.90
# dog          6.0        34.0          102.75
```

## Multiple columns to multiple columns with different functions

[https://stackoverflow.com/questions/14529838/apply-multiple-functions-to-multiple-groupby-columns/53096340](https://stackoverflow.com/questions/14529838/apply-multiple-functions-to-multiple-groupby-columns/53096340)

In [7]:
import numpy as np
df = pd.DataFrame(np.random.rand(4,4), columns=list('abcd'))
df['group'] = [0, 0, 1, 1]
df

          a         b         c         d  group
0  0.641944  0.206275  0.192590  0.559414      0
1  0.906331  0.481903  0.217608  0.884553      0
2  0.852912  0.846029  0.385852  0.001275      1
3  0.047985  0.419928  0.508445  0.662025      1

In [8]:
df.groupby('group').agg({'a':['sum', 'max'], 
                         'b':'mean', 
                         'c':'sum', 
                         'd': lambda x: x.max() - x.min()})

              a                   b         c         d
            sum       max      mean       sum  <lambda>
group
0      1.548275  0.906331  0.344089  0.410198  0.325138
1      0.900898  0.852912  0.632979  0.894296  0.660750